"""Shared controller helpers for snapshot import and export.

Provide reusable request models and utility handlers used by API
controllers to export and restore search structure snapshots.

The module centralizes common snapshot operations in order to avoid
duplicated logic across routers. It defines:

    - A request model used by import endpoints.
    - A helper for exporting the current service state.
    - A helper for restoring a service state from a snapshot.

Snapshots are represented as versioned JSON-compatible dictionaries
generated by the corresponding service implementations.

Author: Juan Esteban Bedoya <jebedoyal@udistrital.edu.co>

This file is part of ComputerScience2 project.

ComputerScience2 is free software: you can redistribute it and/or
modify it under the terms of the GNU General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

ComputerScience2 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with ComputerScience2. If not, see <https://www.gnu.org/licenses/>.
"""

from typing import Any, Dict

from fastapi import HTTPException
from pydantic import BaseModel, Field


class SnapshotRequest(BaseModel):
	"""Represent a snapshot payload used by import endpoints.

	Attributes:
	    snapshot (Dict[str, Any]):
	        Versioned JSON-compatible snapshot containing the
	        serialized structure state and configuration.

	"""

	snapshot: Dict[str, Any] = Field(
		...,
		description='Versioned JSON snapshot',
	)


def handle_export_snapshot(service) -> Dict[str, Any]:
	"""Export the current state of a search structure.

	This helper delegates snapshot generation to the provided
	service instance and returns the serialized structure state.

	Args:
	    service:
	        Search service implementing the ``save_state`` method.

	Returns:
	    Dict[str, Any]:
	        JSON-compatible snapshot representing the current
	        structure state.

	"""
	return service.save_state()


def handle_import_snapshot(
	service,
	request: SnapshotRequest,
) -> Dict[str, Any]:
	"""Restore a search structure from a snapshot.

	This helper delegates snapshot restoration to the provided
	service instance. If the snapshot is invalid or incompatible,
	an HTTP 400 error is raised.

	Args:
	    service:
	        Search service implementing the ``load_state`` and
	        ``save_state`` methods.

	    request (SnapshotRequest):
	        Request containing the snapshot to restore.

	Returns:
	    Dict[str, Any]:
	        Snapshot representing the restored structure state.

	Raises:
	    HTTPException:
	        If the snapshot cannot be restored due to validation
	        or compatibility errors.

	"""
	try:
		service.load_state(request.snapshot)
		return service.save_state()

	except ValueError as exc:
		raise HTTPException(
			status_code=400,
			detail=str(exc),
		)
