from app.services.search.tree.digital_tree import DigitalTree
from app.services.search.tree.multiple_residue_tree import MultipleResidueTree
from app.services.search.tree.simple_residue_tree import SimpleResidueTree

dt = DigitalTree(encoding='ABC')
dt.create()
dt.insert('D')
dt.insert('E')
dt.insert('S')
dt.insert('I')
dt.insert('H')
dt.insert('O')
dt.insert('M')
dt.insert('A')
dt.delete('D')
# print(dt.search('A'))
dt.plot('digital.png')
dt.search_plot('I', 'digital_destacado.png')

# Simple
st = SimpleResidueTree(encoding='ABC')
st.create()
st.insert('D')
st.insert('E')
st.insert('S')
st.insert('I')
st.insert('H')
st.delete('H')
print(st.search('H'))
st.plot('simple.png')
st.search_plot('I', 'simple_destacado.png')

# Múltiple
mt = MultipleResidueTree(m=2, encoding='ABC')
mt.create()
mt.insert('D')
mt.insert('E')
mt.insert('S')
mt.insert('I')
mt.insert('H')
mt.insert('O')
mt.insert('M')
mt.insert('A')
mt.insert('R')
mt.insert('N')
# mt.delete('H')
# print(mt.search('H'))
mt.plot('multiple.png')
mt.search_plot('I', 'multiple_destacado.png')
