"""Domain models for graph structures and derived algorithm results.

Define the core dataclasses used throughout the graph module,
including graph entities, algorithm outputs, matrix-based structures,
coloring results, spanning tree representations, and shortest-path
results. These models provide strongly typed containers shared across
services, algorithms, serializers, and visualization utilities.

Author: Juan Esteban Bedoya <jebedoyal@udistrital.edu.co>

This file is part of ComputerScience2 project.

ComputerScience2 is free software: you can redistribute it and/or
modify it under the terms of the GNU General Public License as
published by the Free Software Foundation, either version 3 of
the License, or (at your option) any later version.

ComputerScience2 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with ComputerScience2. If not, see <https://www.gnu.org/licenses/>.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass(slots=True)
class Vertex:
	"""Represent a graph vertex.

	Store the identity and optional ordinal label associated with a
	vertex inside a graph structure.

	Attributes:
		name (str): Unique vertex identifier.
		ordinal (Optional[int]): Optional ordinal traversal label.

	"""

	name: str
	ordinal: Optional[int] = None


@dataclass(slots=True)
class Edge:
	"""Represent a graph edge.

	Store structural information describing a connection between two
	vertices, including direction and optional weight.

	Attributes:
		name (str): Unique edge identifier.
		source (str): Source vertex name.
		target (str): Target vertex name.
		directed (bool): Whether the edge is directed.
		weight (Optional[float]): Optional edge weight value.

	"""

	name: str
	source: str
	target: str
	directed: bool
	weight: Optional[float] = None


@dataclass(slots=True)
class MSTResult:
	"""Store spanning tree computation results.

	Represent the output generated by minimum or maximum spanning tree
	algorithms, including branches, chords, graph rank, nullity, and
	total accumulated weight.

	Attributes:
		edges (List[str]): Selected spanning tree edge names.
		complement_edges (List[str]): Edges excluded from the tree.
		branches (List[str]): Tree branch edges.
		chords (List[str]): Non-tree chord edges.
		rank (int): Graph rank value.
		nullity (int): Graph nullity value.
		total_weight (float): Total spanning tree weight.

	"""

	edges: List[str] = field(default_factory=list)
	complement_edges: List[str] = field(default_factory=list)
	branches: List[str] = field(default_factory=list)
	chords: List[str] = field(default_factory=list)
	rank: int = 0
	nullity: int = 0
	total_weight: float = 0.0


@dataclass(slots=True)
class PathResult:
	"""Store generic shortest-path algorithm results.

	Provide a reusable container for shortest-path outputs including
	distances, reconstructed paths, and intermediate execution steps.

	Attributes:
		source (str): Source vertex name.
		target (Optional[str]): Target vertex name.
		distances (Dict[str, float]): Distance map from source.
		path (List[str]): Reconstructed shortest path.
		steps (List[Dict[str, Any]]): Intermediate algorithm steps.

	"""

	source: str
	target: Optional[str]
	distances: Dict[str, float] = field(default_factory=dict)
	path: List[str] = field(default_factory=list)
	steps: List[Dict[str, Any]] = field(default_factory=list)


@dataclass(slots=True)
class FloydWarshallResult:
	"""Store Floyd-Warshall shortest-path results.

	Contain distance and predecessor matrices, reconstructed paths,
	and cycle detection information generated by the Floyd-Warshall
	algorithm.

	Attributes:
		distance_matrix (List[List[float]]): All-pairs distance matrix.
		predecessor_matrix (List[List[Optional[str]]]): Predecessor
			matrix used for path reconstruction.
		shortest_paths (Dict[str, Dict[str, List[str]]]): Reconstructed
			shortest paths between all vertex pairs.
		negative_cycle_detected (bool): Whether a negative cycle exists.
		vertex_labels (List[str]): Ordered vertex labels.

	"""

	distance_matrix: List[List[float]] = field(default_factory=list)
	predecessor_matrix: List[List[Optional[str]]] = field(default_factory=list)
	shortest_paths: Dict[str, Dict[str, List[str]]] = field(default_factory=dict)
	negative_cycle_detected: bool = False
	vertex_labels: List[str] = field(default_factory=list)


@dataclass(slots=True)
class CutSetResult:
	"""Store cut-set families and matrix representations.

	Represent cut-set detection results including cut families,
	disconnecting edge sets, and binary matrix representations.

	Attributes:
		cut_sets (List[List[str]]): Detected cut-set families.
		cut_matrix (List[List[int]]): Binary cut-set matrix.
		edge_labels (List[str]): Ordered edge labels.
		disconnecting_sets (List[List[str]]): Edge subsets that
			disconnect the graph.

	"""

	cut_sets: List[List[str]] = field(default_factory=list)
	cut_matrix: List[List[int]] = field(default_factory=list)
	edge_labels: List[str] = field(default_factory=list)
	disconnecting_sets: List[List[str]] = field(default_factory=list)


@dataclass(slots=True)
class DominationResult:
	"""Store domination-set families and domination metrics.

	Contain dominating-set classifications and domination number
	information computed from graph domination algorithms.

	Attributes:
		dominating_sets (List[List[str]]): All dominating sets.
		minimum_dominating_sets (List[List[str]]): Minimum dominating
			sets.
		independent_dominating_sets (List[List[str]]): Independent
			dominating sets.
		domination_number (int): Minimum dominating-set size.

	"""

	dominating_sets: List[List[str]] = field(default_factory=list)
	minimum_dominating_sets: List[List[str]] = field(default_factory=list)
	independent_dominating_sets: List[List[str]] = field(default_factory=list)
	domination_number: int = 0


@dataclass(slots=True)
class MatchingResult:
	"""Store matching families and matching metrics.

	Represent graph matching classifications including maximal and
	maximum matchings together with the matching number.

	Attributes:
		matchings (List[List[str]]): All valid matchings.
		maximal_matchings (List[List[str]]): Maximal matchings.
		maximum_matchings (List[List[str]]): Maximum-cardinality
			matchings.
		matching_number (int): Maximum matching size.

	"""

	matchings: List[List[str]] = field(default_factory=list)
	maximal_matchings: List[List[str]] = field(default_factory=list)
	maximum_matchings: List[List[str]] = field(default_factory=list)
	matching_number: int = 0


@dataclass(slots=True)
class BellmanResult:
	"""Store Bellman lambda algorithm results.

	Contain lambda values, reconstructed paths, and intermediate
	expressions generated during Bellman computations.

	Attributes:
		source (str): Source vertex name.
		target (Optional[str]): Target vertex name.
		lambda_values (Dict[str, float]): Computed lambda values.
		intermediate_steps (List[str]): Intermediate calculation
			steps.
		path (List[str]): Reconstructed shortest path.

	"""

	source: str
	target: Optional[str]
	lambda_values: Dict[str, float] = field(default_factory=dict)
	intermediate_steps: List[str] = field(default_factory=list)
	path: List[str] = field(default_factory=list)


@dataclass(slots=True)
class DijkstraResult:
	"""Store Dijkstra shortest-path execution results.

	Provide shortest-path distances, traversal traces, and path
	reconstruction data produced by Dijkstra's algorithm.

	Attributes:
		source (str): Source vertex name.
		target (Optional[str]): Target vertex name.
		pairs (List[List[Any]]): Evaluated edge-distance pairs.
		definitive_order (List[str]): Definitive visitation order.
		distances (Dict[str, float]): Final shortest-path distances.
		path (List[str]): Reconstructed shortest path.

	"""

	source: str
	target: Optional[str]
	pairs: List[List[Any]] = field(default_factory=list)
	definitive_order: List[str] = field(default_factory=list)
	distances: Dict[str, float] = field(default_factory=dict)
	path: List[str] = field(default_factory=list)


@dataclass(slots=True)
class CircuitResult:
	"""Store graph circuit families and matrix representations.

	Represent detected graph circuits together with binary circuit
	matrices and edge ordering information.

	Attributes:
		circuits (List[List[str]]): Detected circuit families.
		matrix (List[List[int]]): Circuit matrix representation.
		edge_labels (List[str]): Ordered edge labels.

	"""

	circuits: List[List[str]] = field(default_factory=list)
	matrix: List[List[int]] = field(default_factory=list)
	edge_labels: List[str] = field(default_factory=list)


@dataclass(slots=True)
class ColoringResult:
	"""Store graph coloring metrics and equivalence classes.

	Contain vertex and edge coloring information, chromatic metrics,
	and partition classes generated by coloring algorithms.

	Attributes:
		chromatic_number (int): Graph chromatic number.
		chromatic_polynomial (str): Chromatic polynomial expression.
		classes (Dict[str, List[str]]): Vertex coloring classes.
		chromatic_index (int): Edge chromatic index.
		edge_classes (Dict[str, List[str]]): Edge coloring classes.

	"""

	chromatic_number: int = 0
	chromatic_polynomial: str = ''
	classes: Dict[str, List[str]] = field(default_factory=dict)
	chromatic_index: int = 0
	edge_classes: Dict[str, List[str]] = field(default_factory=dict)


@dataclass(slots=True)
class IndependentSetsResult:
	"""Store independent-set families and metrics.

	Represent all, maximal, and maximum independent sets together
	with the graph independence number.

	Attributes:
		all_sets (List[List[str]]): All independent sets.
		independence_number (int): Independence number.
		maximum_sets (List[List[str]]): Maximum independent sets.
		maximal_sets (List[List[str]]): Maximal independent sets.

	"""

	all_sets: List[List[str]] = field(default_factory=list)
	independence_number: int = 0
	maximum_sets: List[List[str]] = field(default_factory=list)
	maximal_sets: List[List[str]] = field(default_factory=list)


@dataclass(slots=True)
class TreeDistanceResult:
	"""Store weighted tree-distance operation results.

	Represent union and intersection computations used to calculate
	the weighted distance between two trees.

	Attributes:
		union_edges (List[str]): Union edge set.
		intersection_edges (List[str]): Intersection edge set.
		union_weight_sum (float): Total union weight.
		intersection_weight_sum (float): Total intersection weight.
		distance (float): Weighted tree distance.
		operations (List[str]): Operations applied during computation.

	"""

	union_edges: List[str] = field(default_factory=list)
	intersection_edges: List[str] = field(default_factory=list)
	union_weight_sum: float = 0.0
	intersection_weight_sum: float = 0.0
	distance: float = 0.0
	operations: List[str] = field(default_factory=list)


@dataclass(slots=True)
class Graph:
	"""Represent a graph and its derived structures.

	Store graph metadata, vertices, edges, and algorithm-generated
	derived structures used across the application.

	Attributes:
		graph_id (str): Unique graph identifier.
		directed (bool): Whether the graph is directed.
		weighted (bool): Whether the graph is weighted.
		vertices (Dict[str, Vertex]): Vertex registry by name.
		edges (Dict[str, Edge]): Edge registry by name.
		derived (Dict[str, Any]): Derived algorithm results and
			auxiliary structures.

	"""

	graph_id: str
	directed: bool
	weighted: bool
	vertices: Dict[str, Vertex] = field(default_factory=dict)
	edges: Dict[str, Edge] = field(default_factory=dict)
	derived: Dict[str, Any] = field(default_factory=dict)
